### PR TITLE
support `Colors` 0.13

### PR DESCRIPTION
**Pull request by t-bltg**
cc @simonbyrne

### CODE REVIEW

**Review by simonbyrne — APPROVED** [review]

**Comment by GregPlowman** [comment]
Thanks for this.
Is it possible to issue a new release now?

**Comment by maleadt** [comment]
https://github.com/JuliaRegistries/General/pull/119638

**Comment by t-bltg** [comment]
@maleadt, the version was already incremented in this PR ;)

**Comment by maleadt** [comment]
I noticed. New request is up.

**Pull request merged**
